// this file will replace modData.json, but it will be kept for backwards compatibility with older builds
// testing for now
modsList = [
    {
        name: "Zerouxbox",
        desc: "Description goes here.",
        imgBG: "mod-background",
        imgIcon: "mod-icon",
        preview: "https://joalor64gh.github.io/",
        downloadPC: "https://joalor64gh.github.io/foreverbox.html",
        downloadAndroid: "https://joalor64gh.github.io/foreverbox.html",
    },
    {
        name: "Eternyx",
        desc: "Description goes here.",
        imgBG: "mod-background",
        imgIcon: "mod-icon",
        preview: "https://joalor64gh.github.io/",
        downloadPC: "https://joalor64gh.github.io/foreverbox.html",
        downloadAndroid: "https://joalor64gh.github.io/foreverbox.html",
    },
    {
        name: "Joalor64's Beatbox",
        desc: "Description goes here.",
        imgBG: "mod-background",
        imgIcon: "mod-icon",
        preview: "https://joalor64gh.github.io/",
        downloadPC: "https://joalor64gh.github.io/foreverbox.html",
        downloadAndroid: "https://joalor64gh.github.io/foreverbox.html",
    },
    {
        name: "Yet Another Generic Sprunki Remake",
        desc: "Description goes here.",
        imgBG: "mod-background",
        imgIcon: "mod-icon",
        preview: "https://joalor64gh.github.io/",
        downloadPC: "https://joalor64gh.github.io/foreverbox.html",
        downloadAndroid: "https://joalor64gh.github.io/foreverbox.html",
    },
    {
        name: "Caribbeanbox",
        desc: "Description goes here.",
        imgBG: "mod-background",
        imgIcon: "mod-icon",
        preview: "https://joalor64gh.github.io/",
        downloadPC: "https://joalor64gh.github.io/foreverbox.html",
        downloadAndroid: "https://joalor64gh.github.io/foreverbox.html",
    },
    {
        name: "Thomasbox",
        desc: "Description goes here.",
        imgBG: "mod-background",
        imgIcon: "mod-icon",
        preview: "https://joalor64gh.github.io/",
        downloadPC: "https://joalor64gh.github.io/foreverbox.html",
        downloadAndroid: "https://joalor64gh.github.io/foreverbox.html",
    },
    {
        name: "Foreverbox",
        desc: "Description goes here.",
        imgBG: "mod-background",
        imgIcon: "mod-icon",
        preview: "https://joalor64gh.github.io/",
        downloadPC: "https://joalor64gh.github.io/foreverbox.html",
        downloadAndroid: "https://joalor64gh.github.io/foreverbox.html",
    }
];